# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtNetwork import QTcpSocket, QNetworkAccessManager, QNetworkRequest
from PyQt5.QtCore import QJsonDocument, QJsonValue, QJsonParseError
from work_thread import TcpThread, HttpThread
from dao import Dao

class Ui_Form(object):
    def __init__(self):
        self.tcp_socket = QTcpSocket()
        self.form = None
        self.threads = []
        self.network_accessmanager = QNetworkAccessManager()
        self.login_reply_object = []
        self.reply_object = None
        self.http_threads = []

    def setupUi(self, Form):
        self.form = Form
        Form.setObjectName("Form")
        Form.resize(713, 782)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout_8.addWidget(self.lineEdit_ip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit_port = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_9.addWidget(self.lineEdit_port)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_connect = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect.clicked.connect(self.on_connect)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.tab)
        self.pushButton_disconnect.clicked.connect(self.on_disconnect)
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout.addWidget(self.pushButton_disconnect)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.spinBox_clients_number_tcp = QtWidgets.QSpinBox(self.tab)
        self.spinBox_clients_number_tcp.setObjectName("spinBox_clients_number_tcp")
        self.horizontalLayout.addWidget(self.spinBox_clients_number_tcp)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.spinBox_interval_tcp = QtWidgets.QSpinBox(self.tab)
        self.spinBox_interval_tcp.setObjectName("spinBox_interval_tcp")
        self.horizontalLayout_6.addWidget(self.spinBox_interval_tcp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_10.addWidget(self.textEdit_2)
        self.pushButton_send = QtWidgets.QPushButton(self.tab)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_10.addWidget(self.pushButton_send)
        self.pushButton_send.clicked.connect(self.on_socket_send)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.spinBox_clients_number = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_clients_number.setObjectName("spinBox_clients_number")
        self.horizontalLayout_12.addWidget(self.spinBox_clients_number)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.spinBox_interval = QtWidgets.QSpinBox(self.tab_2)
        self.spinBox_interval.setObjectName("spinBox_interval")
        self.horizontalLayout_13.addWidget(self.spinBox_interval)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_url = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.horizontalLayout_2.addWidget(self.lineEdit_url)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_send_http = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_send_http.clicked.connect(self.on_http_send)
        self.pushButton_send_http.setObjectName("pushButton_send_http")
        self.verticalLayout_3.addWidget(self.pushButton_send_http)
        self.pushButton_stop = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_stop.clicked.connect(self.on_stop)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout_3.addWidget(self.pushButton_stop)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.textEdit_request = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_request.setObjectName("textEdit_request")
        self.horizontalLayout_4.addWidget(self.textEdit_request)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.textEdit_response = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_response.setObjectName("textEdit_response")
        self.horizontalLayout_5.addWidget(self.textEdit_response)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "ip:"))
        self.label_6.setText(_translate("Form", "port:"))
        self.pushButton_connect.setText(_translate("Form", "connect"))
        self.pushButton_disconnect.setText(_translate("Form", "disconnect"))
        self.label_4.setText(_translate("Form", "clients number:"))
        self.label.setText(_translate("Form", "interval:"))
        self.pushButton_send.setText(_translate("Form", "send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "tcp"))
        self.label_9.setText(_translate("Form", "clients number:"))
        self.label_10.setText(_translate("Form", "interval:"))
        self.label_8.setText(_translate("Form", "method:"))
        self.comboBox.setItemText(0, _translate("Form", "GET"))
        self.comboBox.setItemText(1, _translate("Form", "POST"))
        self.comboBox.setItemText(2, _translate("Form", "PUT"))
        self.comboBox.setItemText(3, _translate("Form", "DELETE"))
        self.label_2.setText(_translate("Form", "url:"))
        self.pushButton_send_http.setText(_translate("Form", "send"))
        self.pushButton_stop.setText(_translate("Form", "stop"))
        self.label_3.setText(_translate("Form", "body:"))
        self.label_7.setText(_translate("Form", "response:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "http"))

    def on_connect(self):
        self.tcp_socket.connectToHost(self.lineEdit_ip.text(), int(self.lineEdit_port.text()))
        if not self.tcp_socket.waitForConnected(2500):
            msg = self.tcp_socket.errorString()
            QtWidgets.QMessageBox.critical(self.form, "Error", msg)
            return False
        for i in range(self.spinBox_clients_number_tcp.value()):
            w = TcpThread()
            w.interval = self.spinBox_interval_tcp.value()
            w.s.connect(self.on_send)
            self.threads.append(w)

    def on_send(self):
        out = QtCore.QByteArray()
        stream = QtCore.QDataStream(out, QtCore.QIODevice.WriteOnly)
        stream.writeQString(self.textEdit_2.toPlainText())
        self.tcp_socket.write(out)

    def on_socket_send(self):
        for t in self.threads:
            t.start()

    def on_disconnect(self):
        for t in self.threads:
            t.is_send = False
    def on_http_send(self):
        d = Dao()
        results = d.get_users(self.spinBox_clients_number.value())
        for r in results:
            data = QtCore.QByteArray()
            json = QJsonDocument.fromJson(data).object()
            json["account"] = r[0]
            json["password"] = r[1]
            outputjson = QJsonDocument(json).toJson(QJsonDocument.Compact)

            url = QtCore.QUrl('http://172.16.10.44/api/v1/login')
            request = QNetworkRequest()
            request.setUrl(url)
            key = QtCore.QByteArray().append('use-agent')
            value = QtCore.QByteArray().append('Mozilla/5.0 (Windows NT 6.1; rvhq,2.0.1) Gecko/20100101 Firefox/4.0.1')
            request.setRawHeader(key, value)
            senda = QtCore.QByteArray()
            senda.append(outputjson)
            network_reply = self.network_accessmanager.post(request, senda)
            network_reply.finished.connect(self.on_login_response)
            self.login_reply_object.append(network_reply)

    def on_login_response(self):
        for r in self.login_reply_object:
            json = QJsonDocument.fromJson(r.readAll(), QJsonParseError())
            if not json.object():
                continue
            token = json.object()["token"].toString()
            w = HttpThread()
            w.interval = self.spinBox_interval.value()
            w.s.connect(self.send_request)
            w.token = token
            w.start()
            self.http_threads.append(w)
    def send_request(self, token):
        url = QtCore.QUrl(self.lineEdit_url.text())
        request = QNetworkRequest()
        request.setUrl(url)
        key = QtCore.QByteArray().append('token')
        value = QtCore.QByteArray().append(token)
        request.setRawHeader(key, value)
        if self.comboBox.currentText() == 'GET':
            self.reply_object = self.network_accessmanager.get(request)
            self.reply_object.finished.connect(self.on_response)
        # elif self.comboBox.currentText() == 'POST':
        #     senda = QtCore.QByteArray()
        #     senda.append(self.textEdit_request)
        #     self.reply_object = self.network_accessmanager.post(request, senda)
        # elif self.comboBox.currentText() == 'PUT':
        #     self.reply_object = self.network_accessmanager.put(request)
    def on_response(self):
        self.textEdit_response.setText(str(self.reply_object.readAll(), encoding='utf-8'))

    def on_stop(self):
        for t in self.http_threads:
            t.is_send = False