# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtNetwork import QTcpSocket

class Ui_Form(object):
    def __init__(self):
        self.tcp_socket = QTcpSocket()
        self.form = None
        self.threads = []
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(357, 320)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_ip = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.horizontalLayout_8.addWidget(self.lineEdit_ip)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.lineEdit_port = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_9.addWidget(self.lineEdit_port)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.pushButton_connect = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.pushButton_connect.clicked.connect(self.tcp_client_start)
        self.horizontalLayout_7.addWidget(self.pushButton_connect)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_interval = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_interval.setObjectName("lineEdit_interval")
        self.horizontalLayout.addWidget(self.lineEdit_interval)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_threads = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_threads.setObjectName("lineEdit_threads")
        self.horizontalLayout_6.addWidget(self.lineEdit_threads)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_10.addWidget(self.textEdit_2)
        self.pushButton_send = QtWidgets.QPushButton(self.tab)
        self.pushButton_send.clicked.connect(self.on_socket_send)
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_10.addWidget(self.pushButton_send)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "ip:"))
        self.label_6.setText(_translate("Form", "port:"))
        self.pushButton_connect.setText(_translate("Form", "connect"))
        self.label.setText(_translate("Form", "interval:"))
        self.label_4.setText(_translate("Form", "clients numbers:"))
        self.pushButton_send.setText(_translate("Form", "send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))

    def tcp_client_start(self):
        self.tcp_socket.connectToHost(self.lineEdit_ip.text(), int(self.lineEdit_port.text()))
        if not self.tcp_socket.waitForConnected(2500):
            msg = self.tcp_socket.errorString()
            QtWidgets.QMessageBox.critical(self.form, "Error", msg)
            return False
        for i in range(int(self.lineEdit_threads.text())):
            w = WorkThread()
            w.s.connect(self.on_send)
            self.threads.append(w)

    def on_send(self):
        out = QtCore.QByteArray()
        stream = QtCore.QDataStream(out, QtCore.QIODevice.WriteOnly)
        stream.writeQString(self.textEdit_2.toPlainText())
        self.tcp_socket.write(out)

    def on_socket_send(self):
        for t in self.threads:
            t.start()
            t.sleep(int(self.lineEdit_interval.text()))


class WorkThread(QtCore.QThread):
    s = QtCore.pyqtSignal()
    def __init__(self):
        super(WorkThread, self).__init__()
    def run(self):
        self.s.emit()